Removes the Export Links from Event Views
moderntribe/products-extensions pull request #55
Opened 2018-04-05 23:14 UTC by nefeline

Ref.:https://central.tri.be/issues/78932

2018-04-06 19:18 UTC, mitogh requested changes
Overall code seems solid just style and formatting  comments.

2018-04-06 19:18 UTC, mitogh commented on tribe-ext-remove-export-links/index.php
> +		return function_exists( 'tribe' ) ? tribe( 'tec.iCal' ) // Current
Just for consistency I think having each result of the condition in a line would be ideal: 

```php
return function_exists( 'tribe' ) ?
	? tribe( 'tec.iCal' ) // current
	: 'Tribe__Events__iCal'; // legacy
```

2018-04-06 19:18 UTC, mitogh commented on tribe-ext-remove-export-links/index.php
> +	 * Makes the extension compatible with older versions of The Events Calendar.
Missing the `@return {type}` tag on the comment

2018-04-06 19:18 UTC, mitogh commented on tribe-ext-remove-export-links/index.php
> +		remove_action( 'tribe_events_single_event_after_the_content', array(
I think you can have this in a single line for consistency same as the second one. 

```php
remove_action( 'tribe_events_single_event_after_the_content', array( $this->ical_provider(), 'single_event_links' ) );
```

2018-04-06 19:18 UTC, mitogh commented on tribe-ext-remove-export-links/index.php
> +	public function init() {
In this particular case I think both functions are attached to the same action `init` it might be easier to just have a single function like: 


```php
public function init() {
	add_action( 'init', array( $this, 'remove_hooks' ) );
}

public function remove_hooks() {
	$provider = $this->ical_provider();
	remove_action( 'tribe_events_single_event_after_the_content', array( $provider, 'single_event_links' ) );
	remove_filter( 'tribe_events_after_footer', array( $provider, 'maybe_add_link' ) );
}
```

2018-04-06 19:18 UTC, mitogh commented on tribe-ext-remove-export-links/index.php
> +}
I think there should be a new line after a block like: 

```php
/*
 * Do not load directly.
 */
if ( ! defined( 'ABSPATH' ) ) {
	die( '-1' );
}

/**
 * Do not load unless Tribe Common is fully loaded.
 */
if ( ! class_exists( 'Tribe__Extension' ) ) {
	return;
}
```

2018-04-11 21:04 UTC, barryhughes commented
Hey @nefeline! We'll want to get this work across to [github.com/mt-support](https://github.com/mt-support/) ‒ no further extensions should be added to this repo.

2018-04-12 20:27 UTC, closed without merging